name: Shell-Commands

on: [push]

jobs: 
    run-shell-command:
        runs-on: ubuntu-latest
        steps:
          - name: eco string
            run: echo "hello world"
          - name: multi line
            run: | 
                node -v
                npm -v
                
