name: GitHub variables test

on:
  workflow_dispatch:
    inputs:
        environment_name:
            type: choice
            description: Select an environment
            options:
            - 'Development'
            - 'Production'
            default: Development

env:
  WORKING_DIR: "./appservice"
  ENV_VAR1: "AAA AAA AAA"
  ENV_VAR2: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  
jobs:
  deploy:
    name: Deployment
    environment:
      name: ${{ github.event.inputs.environment_name }}
      url: ${{ steps.out.outputs.rg_url }}
    runs-on: ubuntu-latest
    env:
      VAR_1: "BBBBB"
      VAR_2: ${{ env.ENV_VAR2 }}
      
    steps:
    - name: Show default environment variables
      shell: bash
      run: |
        echo "Working DIR: $WORKING_DIR"
        echo "VAR1: $ENV_VAR1" 
        echo "VAR2:" ${{ env.ENV_VAR2 }}
