name: GitHub variables test

on:
  workflow_dispatch:
    inputs:
        environment_name:
            type: choice
            description: Select an environment
            options:
            - 'Development'
            - 'Production'
            default: Development

env:
  WORKING_DIR: "./appservice"
  VAR1: "deployment.tfplan"
  Var2: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  
jobs:
  deploy:
    name: Deployment
    environment:
      name: ${{ github.event.inputs.environment_name }}
      url: ${{ steps.out.outputs.rg_url }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Show default environment variables
      shell: bash
      run: |
        echo "subsid $TF_VAR_AZURE_SUBSCRIPTION_ID"
        echo "Subscription ID:" $env.TF_VAR_AZURE_SUBSCRIPTION_ID
        echo "Client ID:" ${{ env.TF_VAR_AZURE_CLIENT_ID }}
