name: GitHub variables test

on:
  workflow_dispatch:
    inputs:
        environment_name:
            type: choice
            description: Select an environment
            options:
            - 'Development'
            - 'Production'
            default: Development

env:
  WORKING_DIR: "./appservice"
  ENV_VAR1: "AAA AAA AAA"
  ENV_VAR2: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  ENV_VAR3: '${{ secrets.SECRET1 }}'
jobs:
  deploy:
    name: Deployment
    environment:
      name: ${{ github.event.inputs.environment_name }}
      url: ${{ steps.out.outputs.rg_url }}
    runs-on: ubuntu-latest
    env:
      VAR_1: "BBBBB"
      VAR_2: $ENV_VAR2
      VAR_3: ${{ environment.ENVIRONMENT_V1 }}
      
    steps:
    - name: Show default environment variables
      shell: bash
      run: |
        echo "Working DIR: $WORKING_DIR"
        echo "ENV_VAR1: $ENV_VAR1" 
        echo "ENV_VAR2:" ${{ env.ENV_VAR2 }}
        echo "ENV_VAR3:" ${{ env.ENV_VAR3 }}
        echo "-----------------------------------"
        echo "VAR_1: ${{ env.VAR_1 }}"
        echo "VAR_2:" ${{ env.VAR_2 }}
        echo "VAR_3:" ${{ env.VAR_3 }}
        
